# This file was generated by GoReleaser. DO NOT EDIT.
cask "burn" do
  version "0.2.8"

  on_macos do
    on_intel do
      sha256 "c1479bfdeaf90ba905392a3f97105a006cda54945133493d423cd899a7d4e77b"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ae0ef6886d47c4b32ee0dc41ed054ff5ed08a0147c6486c11ca3ac4c2c0bd90"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8db58f610c8ca1aa6488b17cfee7fdd0773c3925a3a453570a3cf338a6e392fe"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd6e387f6d88e9532692bac9cfb16040573ced9234b991aaf82fb35447843ee5"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "burn"
  desc "Kubernetes FinOps CLI — analyze costs, find waste, get AI recommendations"
  homepage "https://github.com/tanrikuluozlem/burn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "burn"

  # No zap stanza required

end
