# This file was generated by GoReleaser. DO NOT EDIT.
cask "burn" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "4f3bf1e04b4d44f20a39af25515a7e1b5f5495e43496c403b9d3c65831507a81"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "919630f80dd6fd8a7d1cae8bfdfb31911b9e452ce38295cc82a560031719bf38"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a945b99b8117ce8b5bc5838aa0f6a536432350eba8a5fdf5a56a93c72a770ed2"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ef5254bb6760dec242f0f79120f6f7a65d69d464f96844d01a4b33774bd386f"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "burn"
  desc "Kubernetes FinOps CLI — analyze costs, find waste, get AI recommendations"
  homepage "https://github.com/tanrikuluozlem/burn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "burn"

  # No zap stanza required

end
