# This file was generated by GoReleaser. DO NOT EDIT.
cask "burn" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "b432120a5451ab93ab480d205b35b3e60f7f320777c702b294c51303096261b6"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6d75afacb4903d693e455af484421c441bf94209070f09bfea19b2fb2d33a87"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c2eb9f636fec1853b24a2368447baf71abe5079c9e6ca7f4d34c129391a2a30"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e3f408a61bc0d7ae376a8ec64f06828f3eab9efcbe6103306773c24ef770e44"
      url "https://github.com/tanrikuluozlem/burn/releases/download/v#{version}/burn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "burn"
  desc "Kubernetes FinOps CLI — analyze costs, find waste, get AI recommendations"
  homepage "https://github.com/tanrikuluozlem/burn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "burn"

  # No zap stanza required

end
